# Generated by Django 5.2.4 on 2025-07-22 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BogieChecksheetForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=100, unique=True)),
                ('inspectionBy', models.CharField(max_length=100)),
                ('inspectionDate', models.DateField()),
                ('bogieDetails', models.JSONField()),
                ('bogieChecksheet', models.JSONField()),
                ('bmbcChecksheet', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='WheelSpecificationsForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formNumber', models.CharField(max_length=100, unique=True)),
                ('submittedBy', models.CharField(max_length=100)),
                ('submittedDate', models.DateField()),
                ('fields', models.JSONField()),
            ],
        ),
    ]
